apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastro-deploy
  labels:
    app: cadastro
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cadastro
  template:
    metadata:
      labels:
        app: cadastro
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
        prometheus.io/scheme: "http"
    spec:
      containers:
      - name: cadastro
        image: fbsweb/cadastro:1.0
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 5
        startupProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 5