
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        env:
        - name: REDIS_HOSTS
          value: local:redis-service:6379
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander-service
spec:
  type: NodePort  # Usando NodePort para acesso externo
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081  # Porta acessível externamente
  selector:
    app: redis-commander